language: r
r:
  - bioc-devel
  - bioc-release
# warnings_are_errors: true
cache: packages

services:
  - docker

addons:
  apt:
    packages:
      - libprotobuf-dev
      - libapparmor-dev
      - protobuf-compiler
      - libcurl4-openssl-dev
      - libmagick++-dev

r_packages:
  - covr
  - data.table
  - ggplot2
  - testthat
  - knitr
  - rmarkdown
  - httpuv
  - opencpu
  - protolite
  - Rook
  - unix
  - magick

os:
  - linux
  - osx

bioc_required: true
bioc_packages:
  - BiocCheck
  - GEOquery
  - limma
  - rhdf5
  - BiocStyle

before_install:
#  - if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew unlink python; brew install protobuf; fi
  - R -e 'install.packages("devtools")'

script:
  - R CMD build .
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check "$FILE"
  - bash inst/test_js.sh

after_script:
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  slack:
    rooms:
      - sysbio1:Kt2QCRqnbzJpNE8TvOvgwEMz#phantasus

jobs:
  include:
    - stage: Docker build
      env: DOCKER_TAG="$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER"
      language: minimal
      before_install: skip
      after_script: skip
      after_success: skip
      r_packages: skip
      install: skip
      script: if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
                docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
                docker build -t dzenkova/phantasus --build-arg PHANTASUS_BUILD=$DOCKER_TAG --build-arg GITHUB_PAT=$GITHUB_PAT . ;
                docker tag dzenkova/phantasus dzenkova/phantasus:$DOCKER_TAG ;
                docker push dzenkova/phantasus;
              fi
    - stage: Docker build
      env: DOCKER_TAG="$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER"
      language: minimal
      before_install: skip
      after_script: skip
      after_success: skip
      r_packages: skip
      install: skip
      script: if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_BRANCH" == "develop" ]; then
                docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
                docker build --build-arg PHANTASUS_BUILD=$DOCKER_TAG --build-arg GITHUB_PAT=$GITHUB_PAT -t dzenkova/phantasus:develop . ;
                docker tag dzenkova/phantasus:develop dzenkova/phantasus:$DOCKER_TAG ;
                docker push dzenkova/phantasus:develop;
                docker push dzenkova/phantasus:$DOCKER_TAG;
              fi
# Something always happens to osx bioc-devel builds 
  exclude:
  - os: osx
    r: bioc-devel
