version: "2"
services:
    phantasus:
        env_file:
            - .env
        image: alserglab/phantasus
        ports:
            - "8000:8000"
        volumes:
           - type: bind
             source: $PHANTASUS_CONFIG_DIR
             target: /etc/R/phantasus
           - type: bind
             source: $PHANTASUS_CACHE_DIR
             target: /var/phantasus/cache
           - type: bind
             source: $PHANTASUS_PRELOADED_DIR
             target: /var/phantasus/preloaded


