default:
    host: '0.0.0.0'
    port: 8000
    local_cache:
        cache_root: "!expr getOption('phantasusCacheDir', tempdir())"
        rnaseq_counts:  !expr file.path( getOption("phantasusCacheDir", tempdir()), "counts")
        annot_db: !expr file.path(getOption("phantasusCacheDir", tempdir()), "annotationdb")
        fgsea_pathways: !expr file.path( getOption("phantasusCacheDir", tempdir()), "fgsea")
    preloaded_dir: NULL
    static_root: !expr system.file("www/phantasus.js", package = "phantasus")
    open_in_browser: TRUE
    quiet: TRUE
    external_sources:
        geo_mirrors: !expr getOption('phantasusMirrorPath', "https://ftp.ncbi.nlm.nih.gov")


minimal_cache:
    inherits: default
    external_sources:
        geo_mirrors:
            minimal_cache: "https://ctlab.itmo.ru/files/software/phantasus/minimal-cache"
            true_geo:
        #rnaseq_counts: "https://ctlab.itmo.ru/hsds/?domain=/counts"
        rnaseq_counts: "https://ctlab.itmo.ru/files/software/phantasus/minimal-cache/counts"
        fgsea_pathways: "https://ctlab.itmo.ru/files/software/phantasus/minimal-cache/fgsea"
        annot_db: "https://ctlab.itmo.ru/files/software/phantasus/minimal-cache/annotationdb"
