default:
  host: "0.0.0.0"
  port: 8000
  preloaded_dir: "/var/phantasus/preloaded"
  static_root: !expr system.file('www/phantasus.js', package = 'phantasus')
  cache_root: "/var/phantasus/cache"
  cache_folders:
    geo_path: !expr file.path(cache_root, 'geo/')
    annot_db: !expr file.path(cache_root, 'annotationdb/')
    fgsea_pathways: !expr file.path(cache_root, 'fgsea_pathways/')
    rnaseq_counts: !expr file.path(cache_root, 'rnaseq_counts/')
  internal_ports: [8001, 8002, 8003, 8004, 8005, 8006, 8007, 8008, 8009, 8010]
  geo_mirrors:
    true_geo: "https://ftp.ncbi.nlm.nih.gov"
